server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  datasource: # Only if you're using JPA in the gateway (usually you don't)
    url: jdbc:mysql://localhost:3306/internshipt_db?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

global cors:
  corsConfigurations:
    '[/**]':
      allowedOrigins: "http://localhost:3000"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders: "*"
      allowCredentials: true
